final List<String> subjects = [
  "Algebra",
  "Applied Mathematics",
  "Arabic",
  "Art",
  "Artificial Intelligence",
  "Basics",
  "Biology",
  "Calculus",
  "Chemistry",
  "Christian Religious Education",
  "Computer Science",
  "Critical Thinking",
  "Discover",
  "Dynamics",
  "Economics",
  "English",
  "Entrepreneurship",
  "French",
  "Geography",
  "Geology",
  "German",
  "History",
  "Integrated Science",
  "Islamic Religious Education",
  "Math",
  "National Education",
  "Philosophy",
  "Physical Education",
  "Physics",
  "Psychology and Sociology",
  "Pure Mathematics",
  "Science",
  "Skills",
  "Social Studies",
  "Solid Geometry",
  "Spanish",
  "Statics",
  "Statistics",
];
